// =============================================================================
//  main.c
//  banking portion of the DFP benchmark suite
// =============================================================================
//  Original Author : Liang-Kai Wang, 5/2007
//  Maintainer:       Charles Tsen, 11/2008
// =============================================================================
//  This the main file for the Banking benchmark, part of the decimal floating-
//  point benchmark suite. This benchmark was modified from several resources
//  including the rules and condition of the Citibank Dividend Reward Card, and
//  several mortgage calculation. For details, please refer to the following 
//  paper:
//
//      Wang, Tsen, Jhalani, Schulte  "Benchmarks and Performance Analysis
//      of Decimal Floating-Point Applications" from IEEE International
//      Conference on Computer Design, Oct 2007.
//
//  This benchmark emulates a bank-end server in a bank which is capable of
//  doing credit card, normal deposit and CD, and mortgage service. It takes an
//  input file of daily tasks, generated by a test generator located in the
//  testGen directory. sampleTest directory has some sample tests (both big and
//  small, the big test has a "bin_" prefis).  Please see the README for more 
//  info.
// =============================================================================
//  Copyright (C) 2008 MESA LAB - University of Wisconsin
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.
// =============================================================================
// VERSION AND CVS INFO
// Id: $Id: main.c,v 1.13 2009-05-18 03:07:53 mjanders Exp $
// Date: $Date: 2009-05-18 03:07:53 $
// Author: $Author: mjanders $
// =============================================================================

#include "const.h"
#include "deposit.h"
#include "mortgage.h"
#include "credit_card.h"
#include "decfcn.h"
#include "rdtsc.h"

context_t *setp;  // working round modes

#if defined(NATIVE_GCC_BID)
_IDEC_flags flags = 0x00;      // working flags 
#endif

// COUNTING MICHAEL!!!
unsigned long long add_cycles = 0;
unsigned long long mul_cycles = 0;
unsigned long long quant_cycles = 0;
unsigned long long zero_cycles = 0;
unsigned long long div_cycles = 0;
unsigned long long sqrt_cycles = 0;
unsigned long long sub_cycles = 0;
unsigned long long copy_cycles = 0;
unsigned long long int_cycles = 0;
unsigned long long max_cycles = 0;
unsigned long long minus_cycles = 0;

unsigned long long add_calls = 0;
unsigned long long mul_calls = 0;
unsigned long long quant_calls = 0;
unsigned long long zero_calls = 0;
unsigned long long div_calls = 0;
unsigned long long sqrt_calls = 0;
unsigned long long sub_calls = 0;
unsigned long long copy_calls = 0;
unsigned long long int_calls = 0;
unsigned long long max_calls = 0;
unsigned long long minus_calls = 0;

unsigned long long add_rounded = 0;
unsigned long long int_rounded = 0;
unsigned long long mul_rounded = 0;
unsigned long long rsc_rounded = 0;
unsigned long long div_rounded = 0;

unsigned long long count_begin_func;
unsigned long long count_end_func;
unsigned long long count_overhead;
// END COUNTING MICHAEL!!!



int counter;
int line_num;
#ifdef COUNTING
int mul_total, div_total, add_total, add_minmax_total, add_other_total;
int mul_rounded, div_rounded, add_rounded, add_other_rounded;
//the below one can run on fast pass adder
int add_no_exp_diff;
int add_minmax_no_exp_diff;
int add_other_no_exp_diff;
//this one may run on fast pass
int add_no_right_shifted_diff_exp;
int add_minmax_no_right_shifted_diff_exp;
int add_other_no_right_shifted_diff_exp;
//
int add_op_zero;

//the below can run on fast pass mul
int mul_lt_eq_16_coeff_on_result;
//length of multiplier does matter because mul can be sequential base
int sig_length_multiplier[16];
#endif
#ifdef NEW_FEATURES
//for deposit
dec_t daily_deposit_withdrawl[360], daily_deposit_deposit[360], 
  daily_deposit_cash_flow[360], daily_deposit_interest[360],
  daily_deposit_other[360],
  monthly_deposit_withdrawl, monthly_deposit_deposit, 
  monthly_deposit_cash_flow, monthly_deposit_interest, monthly_deposit_other,
  yearly_deposit_withdrawl, yearly_deposit_deposit, 
  yearly_deposit_cash_flow, yearly_deposit_interest, yearly_deposit_other,
  ytd_deposit_deposit, ytd_deposit_withdrawl, 
  ytd_deposit_cash_flow, ytd_deposit_interest, ytd_deposit_other; 
//for mortgage
dec_t daily_mortgage_open[360], daily_mortgage_interest[360],
  daily_mortgage_receive[360], daily_mortgage_other[360],
  daily_mortgage_cash_flow[360],
  monthly_mortgage_open, monthly_mortgage_interest,
  monthly_mortgage_receive, monthly_mortgage_other, monthly_mortgage_cash_flow,
  yearly_mortgage_open, yearly_mortgage_interest,
  yearly_mortgage_receive, yearly_mortgage_other, yearly_mortgage_cash_flow,
  ytd_mortgage_open, ytd_mortgage_interest,
  ytd_mortgage_receive, ytd_mortgage_other, ytd_mortgage_cash_flow;
//for credit card
dec_t daily_cc_purchase_debt[360], daily_cc_bx_debt[360], 
  daily_cc_ca_debt[360], daily_cc_interest[360], daily_cc_pay[360],
  daily_cc_other[360],
  monthly_cc_purchase_debt, monthly_cc_bx_debt, monthly_cc_ca_debt, 
  monthly_cc_interest, monthly_cc_pay, monthly_cc_other,
  yearly_cc_purchase_debt, yearly_cc_bx_debt, yearly_cc_ca_debt,
  yearly_cc_interest, yearly_cc_pay, yearly_cc_other,
  ytd_cc_purchase_debt, ytd_cc_bx_debt, ytd_cc_ca_debt,
  ytd_cc_interest, ytd_cc_pay, ytd_cc_other;

#endif
int initialization(FILE **conversion_rate_file_ptr,
                   FILE **deposit_rate_file_ptr,
		   FILE **mort_rate_file_ptr, FILE *tcm_rate_file_ptr,
                   FILE *prime_rate_file_ptr,
                   deposit_rate_t* deposit_rate, dec_t **conversion_rate,
		   mort_rate_t *mort_rate, dec_t *tcm_rate,
                   dec_t *prime_rate,
		   cc_const_t *cc_const, cc_rate_t *cc_rate){
  int i;
#ifdef COUNTING
  mul_total = 0, div_total = 0, add_total = 0;
  add_minmax_total = 0, add_other_total = 0;
  add_op_zero = 0;
  mul_rounded = 0, div_rounded = 0, add_rounded = 0, add_other_rounded = 0;
  add_no_exp_diff = 0, add_minmax_no_exp_diff = 0, add_other_no_exp_diff = 0;
  add_no_right_shifted_diff_exp = 0, add_minmax_no_right_shifted_diff_exp = 0;
  add_other_no_right_shifted_diff_exp = 0;
  mul_lt_eq_16_coeff_on_result = 0;
  for (i=0; i<16; i++)
    sig_length_multiplier[i] =0;
#endif
#ifdef NEW_FEATURES
  for (i=0; i<360; i++){
    ZERO64(daily_deposit_withdrawl[i]);
    ZERO64(daily_deposit_deposit[i]);
    ZERO64(daily_deposit_cash_flow[i]);
    ZERO64(daily_deposit_interest[i]);
    ZERO64(daily_deposit_other[i]);
  }
  ZERO64(monthly_deposit_withdrawl);
  ZERO64(monthly_deposit_deposit); 
  ZERO64(monthly_deposit_cash_flow); 
  ZERO64(monthly_deposit_interest); 
  ZERO64(monthly_deposit_other); 
  ZERO64(yearly_deposit_withdrawl); 
  ZERO64(yearly_deposit_deposit); 
  ZERO64(yearly_deposit_cash_flow); 
  ZERO64(yearly_deposit_interest); 
  ZERO64(yearly_deposit_other); 
  ZERO64(ytd_deposit_deposit); 
  ZERO64(ytd_deposit_withdrawl); 
  ZERO64(ytd_deposit_cash_flow); 
  ZERO64(ytd_deposit_interest); 
  ZERO64(ytd_deposit_other);
#endif
  for (i=0; i<2*COUNTRIES; i++) {
    conversion_rate[i] = calloc(2, sizeof(dec_t));
  }
  constdef(conversion_rate, cc_const);
  //Currency Conversion Rate Table
  openConversionRateFile(conversion_rate_file_ptr);
  updateConversionTable(conversion_rate, conversion_rate_file_ptr);
  //Deposit Rate Table
  openDepositRateFile(deposit_rate_file_ptr);
  updateDepositRateTable(deposit_rate, deposit_rate_file_ptr);
  //Mortgage Rate Table
  openMortgageRateFile(mort_rate_file_ptr);
  updateMortgageRate(mort_rate_file_ptr, mort_rate);
  //Treasury Constant Maturity Rate Table
  updateTCMRateFile(tcm_rate, tcm_rate_file_ptr);
  //Update the Prime Rate Table
  updatePrimeRateFile(prime_rate, prime_rate_file_ptr);
  getCCRate(cc_rate, cc_const, *prime_rate);
  return 0;
}

int processing(htab *cd_table, htab *checking_table, htab *mortgage_table, 
	       htab *cc_table, 
	       deposit_rate_t *deposit_rate, FILE *cmd_file_ptr, 
	       cmd_t *this_cmd, mort_rate_t *mort_rate, 
	       dec_t **conversion_rate, dec_t *tcm_rate,
	       cc_const_t *cc_const, cc_rate_t *cc_rate, dec_t *prime_rate,
	       FILE *prime_rate_file_ptr,
	       FILE **conversion_rate_file_ptr, FILE **deposit_rate_file_ptr,
	       FILE **mort_rate_file_ptr, FILE *tcm_rate_file_ptr,
	       FILE *fout){
  int ret;
  int prime_rate_change;
#ifdef DEBUG
  char input_str[STR_MAX_LENGTH];
#endif
  line_num = 1;
  while ((ret = parse_cmd(cmd_file_ptr, this_cmd))!=EOF){
    //If not a good return from parse_cmd, continue!
    if (ret<0) continue;
    line_num++;
    //fprintf(stderr, "line num is %d\n", line_num);
    if (this_cmd->action==NEXT_DAY) {
#ifdef DEBUG
      errorPrint(LOC, INFO_CODE, INFO_CODE, fout,
                 "Processing Deposit Accounts\n");
#endif
      //NOTE: Prime rate table needs to be updated before processing
      //      credit card accounts
#ifdef DEBUG
      errorPrint(LOC, INFO_CODE, INFO_CODE, fout, "Updating Prime Rate Table\n");
#endif
      prime_rate_change = updatePrimeRateFile(prime_rate, prime_rate_file_ptr);
      //Parse the new rate to the CC Rate if needed
      if (prime_rate_change==1)
        getCCRate(cc_rate, cc_const, *prime_rate);
#ifdef DEBUG
      errorPrint(LOC, INFO_CODE, INFO_CODE, fout,
                 "Updating Currency Conversion Rate Table\n");
#endif
      updateConversionTable(conversion_rate, conversion_rate_file_ptr);
#ifdef DEBUG
      errorPrint(LOC, INFO_CODE, INFO_CODE, fout, "Updating CD Rate Table\n");
#endif
      updateDepositRateTable(deposit_rate, deposit_rate_file_ptr);
#ifdef DEBUG
      errorPrint(LOC, INFO_CODE, INFO_CODE, fout,
                 "Updating Mortgage Rate Table\n");
#endif
      updateMortgageRate(mort_rate_file_ptr, mort_rate);
#ifdef DEBUG
      errorPrint(LOC, INFO_CODE, INFO_CODE, fout, "Updating TCM Rate Table\n");
#endif
      updateTCMRateFile(tcm_rate, tcm_rate_file_ptr);
      //Handle deposit account (CD first, then Checking)
      endOfTheDayDeposit(cd_table, checking_table, fout, deposit_rate
#ifdef NEW_FEATURES
			 ,conversion_rate
#endif
);
#ifdef DEBUG
      errorPrint(LOC, INFO_CODE, INFO_CODE, fout,
                 "Processing Mortgage Accounts\n");
#endif
      //Handle mortgage account
      endOfTheDayMortgage(mortgage_table, checking_table, 
			  fout, conversion_rate, deposit_rate, mort_rate,
                          *tcm_rate);
#ifdef DEBUG
      errorPrint(LOC, INFO_CODE, INFO_CODE, fout,
                 "Processing Credit Card Accounts\n");
#endif
      endOfTheDayCreditCard(cc_table, checking_table, fout, conversion_rate, 
			    deposit_rate, cc_rate, cc_const, 
			    prime_rate_change);
      //Lastly, increment the day count
      counter++;
      myfprintf(stderr, "End of Day %d\n", counter);
    }
    else if (this_cmd->acct_type==CD){
      if (this_cmd->action==CD_CK_OPEN){
#ifdef DEBUG
        mysprintf(input_str, "%s opens a CD account\n",
		  this_cmd->acct_no);
        errorPrint(LOC, INFO_CODE, INFO_CODE, fout, input_str);
#endif
	ret = deposit_acct_open(cd_table, this_cmd->acct_no, this_cmd->fund,
				this_cmd->length, CD, this_cmd->select, 
				PAY_DATE, fout, 
				&deposit_rate[this_cmd->select]
#ifdef NEW_FEATURES
				,conversion_rate
#endif
);
      }
      else if (this_cmd->action==CD_CK_INQUIRY){
#ifdef DEBUG
        mysprintf(input_str, "%s inquiries his/her CD account\n",
                this_cmd->acct_no);
        errorPrint(LOC, INFO_CODE, INFO_CODE, fout, input_str);
#endif
	deposit_acct_inquiry(cd_table, this_cmd->acct_no, fout);
      }
      else if (this_cmd->action==CD_SET_CLOSE) {
#ifdef DEBUG
        mysprintf(input_str, "Mark Close %s's CD account\n", 
		  this_cmd->acct_no);
        errorPrint(LOC, INFO_CODE, INFO_CODE, fout, input_str);
#endif
	deposit_mark_close(cd_table, this_cmd->acct_no, fout);
      }
      else if (this_cmd->action==CD_EXTEND) {
#ifdef DEBUG
        mysprintf(input_str, "Mark Extend %s's CD account\n", 
		  this_cmd->acct_no);
        errorPrint(LOC, INFO_CODE, INFO_CODE, fout, input_str);
#endif
        deposit_mark_extend(cd_table, this_cmd->acct_no, fout);
      }
      else if (this_cmd->action==CD_CK_CLOSE) {
#ifdef DEBUG
        mysprintf(input_str, "Close %s's CD account\n", this_cmd->acct_no);
        errorPrint(LOC, INFO_CODE, INFO_CODE, fout, input_str);
#endif
	deposit_acct_close(cd_table, this_cmd->acct_no, conversion_rate, CD, 
			   fout, deposit_rate);
      }
      else if (this_cmd->action==CD_CK_DEPOSIT) {
#ifdef DEBUG
        mysprintf(input_str, "Deposit to %s's CD account\n", 
		  this_cmd->acct_no);
        errorPrint(LOC, INFO_CODE, INFO_CODE, fout, input_str);
#endif
	money_deposit(cd_table, this_cmd->acct_no, this_cmd->fund, 
		      conversion_rate, this_cmd->select, fout);
      }
      else if (this_cmd->action==CD_CK_WITHDRAWL) {
#ifdef DEBUG
        mysprintf(input_str, "Withdrawl to %s's CD account\n", 
		  this_cmd->acct_no);
        errorPrint(LOC, INFO_CODE, INFO_CODE, fout, input_str);
#endif
	money_withdrawl(cd_table, this_cmd->acct_no, this_cmd->select,
			this_cmd->fund, conversion_rate, fout,
			deposit_rate);
      }
      else if (this_cmd->action==WIRETRANSFER) {
        //[Account number] [ACTION] [$] [USELESS+TO_CURRENCY] [FROM_CURRENCY]
#ifdef DEBUG
        mysprintf(input_str, "Wire transfer not allow in CD account\n");
        errorPrint(LOC, WARNING_CODE, CD_NO_WIRETX, fout, input_str);
#endif
      }
      else {
	myfprintf(stderr, "Wrong Action\n");
	myexit(-1);
      }
    }
    else if (this_cmd->acct_type==CHECKING){
      if (this_cmd->action==CD_CK_OPEN){
#ifdef DEBUG
        mysprintf(input_str, "%s opens a CHECKING account\n",
                this_cmd->acct_no);
        errorPrint(LOC, INFO_CODE, INFO_CODE, fout, input_str);
#endif
	ret = deposit_acct_open(checking_table, this_cmd->acct_no, 
				this_cmd->fund,
				this_cmd->length, CHECKING, this_cmd->select,
				PAY_DATE, fout,
				&deposit_rate[this_cmd->select]
#ifdef NEW_FEATURES
                                ,conversion_rate
#endif
);
      }
      else if (this_cmd->action==CD_CK_INQUIRY){
#ifdef DEBUG
        mysprintf(input_str, "%s inquiries his/her CHECKING account\n",
		  this_cmd->acct_no);
        errorPrint(LOC, INFO_CODE, INFO_CODE, fout, input_str);
#endif
        deposit_acct_inquiry(checking_table, this_cmd->acct_no, fout);
      }
      else if ((this_cmd->action==CD_SET_CLOSE)||
	       (this_cmd->action==CD_EXTEND)){
#ifdef DEBUG
        errorPrint(LOC, WARNING_CODE, ACCT_TYPE_WRONG, fout, 
		   "SET Close or Extend is not supported in Checking account");
#endif
      }
      else if (this_cmd->action==CD_CK_CLOSE) {
#ifdef DEBUG
        mysprintf(input_str, "Close %s's CD account\n", this_cmd->acct_no);
        errorPrint(LOC, INFO_CODE, INFO_CODE, fout, input_str);
#endif
        deposit_acct_close(checking_table, this_cmd->acct_no, conversion_rate,
			   CHECKING, fout, NULL);
      }
      else if (this_cmd->action==CD_CK_DEPOSIT) {
#ifdef DEBUG
        mysprintf(input_str, "Deposit to %s's CHECKING account\n", 
		this_cmd->acct_no);
        errorPrint(LOC, INFO_CODE, INFO_CODE, fout, input_str);
#endif
        money_deposit(checking_table, this_cmd->acct_no, this_cmd->fund,
                      conversion_rate, this_cmd->select, fout);
      }
      else if (this_cmd->action==CD_CK_WITHDRAWL) {
#ifdef DEBUG
        mysprintf(input_str, "Withdrawl to %s's CHECKING account\n",
		  this_cmd->acct_no);
        errorPrint(LOC, INFO_CODE, INFO_CODE, fout, input_str);
#endif
        money_withdrawl(checking_table, this_cmd->acct_no, this_cmd->select,
                        this_cmd->fund, conversion_rate, fout,
                        deposit_rate);
      }
      else if (this_cmd->action==WIRETRANSFER) {
	//[Account number] [ACTION] [$] [USELESS+TO_CURRENCY] [FROM_CURRENCY]
	dec_t transaction, processFee, out;
#ifdef DEBUG
	mysprintf(input_str, "%s performs Wire-transfer\n", this_cmd->acct_no);
	errorPrint(LOC, INFO_CODE, INFO_CODE, fout, input_str);
#endif
	wireTransfer(checking_table, this_cmd->select/10, 
		     this_cmd->acct_no, this_cmd->select%10, 
		     this_cmd->fund, &out, &transaction,
		     &processFee, conversion_rate, fout);
      }
      else {
	myfprintf(stderr, "Wrong Action\n");
	myexit(-1);
      }
    }
    else if ((this_cmd->acct_type>=MORTGAGE)&&
             (this_cmd->acct_type!=CREDIT_CARD)){
      if (this_cmd->action==MORT_OPEN) {
#ifdef DEBUG
        mysprintf(input_str, "%s opens a mortgage account\n", 
		  this_cmd->acct_no);
        errorPrint(LOC, INFO_CODE, INFO_CODE, fout, input_str);
#endif
	mortgage_acct_open(mortgage_table, checking_table, 
			   mort_rate,  this_cmd->length, 
			   this_cmd->fund, this_cmd->str1, 
			   this_cmd->acct_no, this_cmd->acct_type, 
			   this_cmd->select,
			   fout);
      }
      else if (this_cmd->action==MORT_INQUIRY){
#ifdef DEBUG
        mysprintf(input_str, "%s inquiries his/her mortgage account\n",
		  this_cmd->acct_no);
        errorPrint(LOC, INFO_CODE, INFO_CODE, fout, input_str);
#endif
	mortgage_acct_inquiry(mortgage_table, this_cmd->acct_no, fout);
      }
      else if (this_cmd->action==MORT_REFINANCE){
#ifdef DEBUG
        mysprintf(input_str, "%s refinances his/her mortgage account\n",
		  this_cmd->acct_no);
        errorPrint(LOC, INFO_CODE, INFO_CODE, fout, input_str);
#endif
	mortgage_acct_refinance(mortgage_table, checking_table,
				mort_rate, this_cmd->length,
				this_cmd->acct_no, this_cmd->acct_type,
				this_cmd->select, fout);
      }
      else if (this_cmd->action==MORT_CLOSE) {
#ifdef DEBUG
        mysprintf(input_str, "%s closes his/her mortgage account\n",
		  this_cmd->acct_no);
        errorPrint(LOC, INFO_CODE, INFO_CODE, fout, input_str);
#endif
	mortgage_acct_close(mortgage_table, this_cmd->acct_no, fout);
      }
      else if (this_cmd->action==MORT_PAY) {
#ifdef DEBUG
        mysprintf(input_str, "%s pays his/her mortgage account\n",
		  this_cmd->acct_no);
        errorPrint(LOC, INFO_CODE, INFO_CODE, fout, input_str);
#endif
	mortgage_acct_pay(mortgage_table, this_cmd->acct_no, fout);
      }
      else{ //schedule table (this should be moved to personal finance later!
#ifdef DEBUG
        mysprintf(input_str, "%s inquiries the schedule table\n",
		  this_cmd->acct_no);
        errorPrint(LOC, INFO_CODE, INFO_CODE, fout, input_str);
#endif
        this_cmd->acct_type = this_cmd->acct_type-MORTGAGE;
        scheduleTable(fout, (this_cmd->fund), this_cmd->length, mort_rate,
                      this_cmd->acct_type);
      }
    }
    else if (this_cmd->acct_type == CREDIT_CARD){
#ifdef DEBUG
      mysprintf(input_str, "Handling %s's Credit Card account\n",
		this_cmd->acct_no);
      errorPrint(LOC, INFO_CODE, INFO_CODE, fout, input_str);
#endif
      if (this_cmd->action==CC_OPEN) {
        credit_card_acct_open(cc_table, checking_table, this_cmd->acct_no,
                              cc_rate, cc_const,
                              (this_cmd->fund),
                              this_cmd->select,
                              fout);
      }
      else if (this_cmd->action==CC_INQUIRY) {
#ifdef DEBUG
        mysprintf(input_str, "%s inquiries his/her Credit Card account\n",
		  this_cmd->acct_no);
        errorPrint(LOC, INFO_CODE, INFO_CODE, fout, input_str);
#endif
	credit_card_acct_inquiry(cc_table, this_cmd->acct_no, fout);
      }
      else if (this_cmd->action==CC_CLOSE) {
#ifdef DEBUG
        mysprintf(input_str, "%s closes his/her Credit Card account\n",
		  this_cmd->acct_no);
        errorPrint(LOC, INFO_CODE, INFO_CODE, fout, input_str);
#endif
	credit_card_acct_close(cc_table, this_cmd->acct_no, fout);
      }
      else if (this_cmd->action==CC_PAY) {
#ifdef DEBUG
        mysprintf(input_str, "%s pays his/her Credit Card account\n",
		  this_cmd->acct_no);
        errorPrint(LOC, INFO_CODE, INFO_CODE, fout, input_str);
#endif
	credit_card_acct_pay(cc_table, this_cmd->acct_no, this_cmd->select,
			     this_cmd->fund, fout);
      }
      else{
#ifdef DEBUG
        mysprintf(input_str,
		  "A transaction is posted to %s Credit Card account\n",
		  this_cmd->acct_no);
        errorPrint(LOC, INFO_CODE, INFO_CODE, fout, input_str);

#endif
	credit_card_acct_debt(cc_table, this_cmd->acct_no, this_cmd->select/10,
			      conversion_rate, fout,
			      cc_const, this_cmd->select%10,
			      this_cmd->fund);

      }
    }
    else {
      errorPrint(LOC, WARNING_CODE, WRONG_ACTION, stderr,
		 "###### Wrong Action. This cmd is skipped ######");
    }
#if defined(BID)
    if((__bid_IDEC_glbflags & BID_FLAG_MASK) == 0){
      char input_str[STR_MAX_LENGTH];
      mysprintf(input_str, "[END CHECK] decContext in Bad Status: 0x%08x\n",
		__bid_IDEC_glbflags);
      errorPrint(LOC, ERROR_CODE, ERROR_CODE, stderr, input_str);
    }
#elif defined(NATIVE_GCC_BID)
    if((flags & BID_FLAG_MASK) == 0){
      char input_str[STR_MAX_LENGTH];
      //mysprintf(input_str, "[END CHECK] decContext in Bad Status: 0x%08x\n",
	//	flags);
      //errorPrint(LOC, ERROR_CODE, ERROR_CODE, stderr, input_str);
    }
#else
    if (setp->status & DEC_Errors){
      char input_str[STR_MAX_LENGTH];
      mysprintf(input_str, "[END CHECK] decContext in Bad Status: 0x%08x, Status: %s\n",
		setp->status, decContextStatusToString(setp));
      errorPrint(LOC, ERROR_CODE, ERROR_CODE, stderr, input_str);
    }
#endif
  }
  return 0;
}

int main(int argc, char *argv[]){
  unsigned long long begin_time, end_time, total_time; // for read time stamp counter
  htab *cd_table, *checking_table, *mortgage_table, *cc_table;
  char cmd_file[PATHNAME_MAX_LENGTH];
  context_t set;
  FILE *conversion_rate_file_ptr[COUNTRIES*2];
  FILE *deposit_rate_file_ptr[COUNTRIES+1];
  deposit_rate_t deposit_rate[COUNTRIES+1];
  dec_t *conversion_rate[2*COUNTRIES];
  FILE *mort_rate_file_ptr[4];
  FILE *tcm_rate_file_ptr;
  FILE *prime_rate_file_ptr;
  FILE *cmd_file_ptr;
  mort_rate_t mort_rate;
  //Credit Card
  cc_const_t cc_const;
  cc_rate_t cc_rate;
  dec_t tcm_rate;
  dec_t prime_rate;
  cmd_t this_cmd;
  if (argc!=2){
    myfprintf(stderr, "[USAGE] cmd cmd_file\n");
    myexit(-1);
  }

  
 // start loop here
 total_time = 0; 
 int loop_counter;
 for(loop_counter = 0 ; loop_counter < 10 ; loop_counter++) {
  mysprintf(cmd_file, "%s", argv[1]);
  FILEOPEN(cmd_file_ptr, cmd_file, "rb");

#if defined(BID) || defined(NATIVE_GCC_BID)
 #if defined(WIDTH64)
  FILEOPEN(tcm_rate_file_ptr, "datafile/bin/1YearTCM.txt.bid", "rb");
  FILEOPEN(prime_rate_file_ptr, "datafile/bin/Prime_rate.txt.bid", "rb");
 #else
  FILEOPEN(tcm_rate_file_ptr, "datafile/bin/1YearTCM.txt.bid128", "rb");
  FILEOPEN(prime_rate_file_ptr, "datafile/bin/Prime_rate.txt.bid128", "rb");
 #endif //width
#else
 #if defined(WIDTH64)
  FILEOPEN(tcm_rate_file_ptr, "datafile/bin/1YearTCM.txt.b64", "rb");
  FILEOPEN(prime_rate_file_ptr, "datafile/bin/Prime_rate.txt.b64", "rb");
 #else
  FILEOPEN(tcm_rate_file_ptr, "datafile/bin/1YearTCM.txt.b128", "rb");
  FILEOPEN(prime_rate_file_ptr, "datafile/bin/Prime_rate.txt.b128", "rb");
 #endif //width
#endif
 



  CONTEXTDEFAULT(set, 0);
  setp = &set;
  counter = 0;
  myfprintf(stderr, "Start of the Banking benchmark\n");
  begin_time = rdtsc();
  ZERO64(prime_rate);
  initialization(conversion_rate_file_ptr, deposit_rate_file_ptr,
		 mort_rate_file_ptr, tcm_rate_file_ptr,
                 prime_rate_file_ptr, 
		 deposit_rate, conversion_rate, 
		 &mort_rate, &tcm_rate, &prime_rate,
		 &cc_const, &cc_rate);

  cd_table = hcreate(8);          /* create hash table */
  checking_table = hcreate(8);
  mortgage_table = hcreate(8);
  cc_table = hcreate(8);

  processing(cd_table, checking_table, mortgage_table, cc_table,
	     deposit_rate, cmd_file_ptr, &this_cmd, &mort_rate,
	     conversion_rate, &tcm_rate, &cc_const, &cc_rate, &prime_rate,
	     prime_rate_file_ptr,
	     conversion_rate_file_ptr, deposit_rate_file_ptr,
	     mort_rate_file_ptr, tcm_rate_file_ptr,
	     stderr);
  myfprintf(stderr, "The number of CD accounts: %d\n", (int)hcount(cd_table));
#ifdef DEBUG
  myfprintf(stderr, "The active CD accounts includes:\n");
#endif
  while (hcount(cd_table)){  /* while the table is not empty */
#ifdef DEBUG
    deposit_acct_t *this_acct;
    this_acct = (deposit_acct_t *)hstuff(cd_table);
    myfprintf(stderr, "%s, ", this_acct->acct_no);
#endif
    myfree(hstuff(cd_table));
    myfree(hkey(cd_table));            /* free memory for the line */
    hdel(cd_table);                /* delete from hash table */
  }
  myfprintf(stderr, "\nThe number of Checking accounts: %d\n", (int)hcount(checking_table));
#ifdef DEBUG
  myfprintf(stderr, "The active Checking accounts includes:");
#endif
  while (hcount(checking_table)){  /* while the table is not empty */
#ifdef DEBUG
    deposit_acct_t *this_acct;
    this_acct = (deposit_acct_t *)hstuff(checking_table);
    myfprintf(stderr, "%s, ", this_acct->acct_no);
#endif
    myfree(hstuff(checking_table));
    myfree(hkey(checking_table));            /* free memory for the line */
    hdel(checking_table);                /* delete from hash table */
  }
  myfprintf(stderr, "\nThe number of Mortgage accounts: %d\n", (int)hcount(mortgage_table));
#ifdef DEBUG
  myfprintf(stderr, "The active Mortgage accounts includes:");
#endif
  while (hcount(mortgage_table)){  /* while the table is not empty */
#ifdef DEBUG
    mort_acct_t *this_acct;
    this_acct = (mort_acct_t *)hstuff(mortgage_table);
    myfprintf(stderr, "%s, ", this_acct->acct_no);
#endif
    myfree(hstuff(mortgage_table));
    myfree(hkey(mortgage_table));            /* free memory for the line */
    hdel(mortgage_table);                /* delete from hash table */
  }
  myfprintf(stderr, "\nThe number of Credit Card accounts: %d\n", (int)hcount(cc_table));
#ifdef DEBUG
  myfprintf(stderr, "The active Credit Card accounts includes:");
#endif
  while (hcount(cc_table)){  /* while the table is not empty */
#ifdef DEBUG
    cc_acct_t *this_acct;
    this_acct = (cc_acct_t *)hstuff(cc_table);
    myfprintf(stderr, "%s, ", this_acct->acct_no);
#endif
    myfree(hstuff(cc_table));
    myfree(hkey(cc_table));            /* free memory for the line */
    hdel(cc_table);                /* delete from hash table */
  }
  myfprintf(stderr, "\n");

  hdestroy(cd_table);                         /* destroy hash table */
  hdestroy(checking_table);                         /* destroy hash table */
  hdestroy(mortgage_table);
  hdestroy(cc_table);
  end_time = rdtsc();
  myfprintf(stderr, "End of the Banking benchmark\n");
  closeDepositRateFile(deposit_rate_file_ptr);
  closeConversionRateFile(conversion_rate_file_ptr);
  closeMortgageRateFile(mort_rate_file_ptr);
#ifdef COUNTING
  decimal_printout(stderr);
#endif
  total_time += (end_time - begin_time);
  myprintf("Total benchmark run_time: %lld\n", total_time);
/*
  myprintf("%ld,", add_calls);
  myprintf("%ld\n", add_cycles);
  myprintf("%ld,", copy_calls);
  myprintf("%ld\n", copy_cycles);
  myprintf("%ld,", div_calls);
  myprintf("%ld\n", div_cycles);
  myprintf("%ld,", int_calls);
  myprintf("%ld\n", int_cycles);
  myprintf("%ld,", max_calls);
  myprintf("%ld\n", max_cycles);
  myprintf("%ld,", minus_calls);
  myprintf("%ld\n", minus_cycles);
  myprintf("%ld,", mul_calls);
  myprintf("%ld\n", mul_cycles);
  myprintf("%ld,", sub_calls);
  myprintf("%ld\n", sub_cycles);
  myprintf("%ld,", zero_calls);
  myprintf("%ld\n", zero_cycles);

  printf("Add rounded: %ld\n", add_rounded);
  printf("Int rounded: %ld\n", int_rounded);
  printf("Mul rounded: %ld\n", mul_rounded);
  printf("Mul rounded: %ld\n", rsc_rounded);
  printf("Div rounded: %ld\n", div_rounded);
*/
/*
  printf("Average cycles for add: %lld\n", add_cycles/add_calls); 
  printf("Average cycles for copy: %lld\n", copy_cycles/copy_calls); 
  printf("Average cycles for div: %lld\n", div_cycles/div_calls); 
  printf("Average cycles for int: %lld\n", int_cycles/int_calls); 
  printf("Average cycles for max: %lld\n", max_cycles/max_calls); 
  printf("Average cycles for minus: %lld\n", minus_cycles/minus_calls); 
  printf("Average cycles for mul: %lld\n", mul_cycles/mul_calls); 
  printf("Average cycles for sub: %lld\n", sub_cycles/sub_calls); 
  printf("Average cycles for zero: %lld\n", zero_cycles/zero_calls); 
  */

  } // end loop

  return SUCCESS;
}
