ln -sf ../../decNumber/decQuad.h
ln -sf ../../decNumber/decPacked.h
ln -sf ../../decNumber/decPacked.c
ln -sf ../../decNumber/decNumberLocal.h
ln -sf ../../decNumber/decNumber.h
ln -sf ../../decNumber/decNumber.c
ln -sf ../../decNumber/decimal64.h
ln -sf ../../decNumber/decimal64.c
ln -sf ../../decNumber/decimal32.h
ln -sf ../../decNumber/decimal32.c
ln -sf ../../decNumber/decimal128.h
ln -sf ../../decNumber/decimal128.c
ln -sf ../../decNumber/decDPD.h
ln -sf ../../decNumber/decDouble.h
ln -sf ../../decNumber/decDouble.c
ln -sf ../../decNumber/decContext.h
ln -sf ../../decNumber/decContext.c
ln -sf ../../decNumber/decCommon.c
ln -sf ../../decNumber/decBasic.c
ln -sf ../../decNumber/LINUXDecFloats.a
ln -sf ../../decNumber/LINUXDecNum.a
ln -sf ../../IntelRDFPMathLib10U1/LIBRARY/bid_functions.h
ln -sf ../../IntelRDFPMathLib10U1/LIBRARY/bid_conf.h
ln -sf ../../IntelRDFPMathLib10U1/LIBRARY/libbid_glbflags.a
