// =============================================================================
//  rdtsc.h
//  read time stamp counter header file, for measurement on ia32, x86-64,
// and powerpc
// =============================================================================
//  Original Author : http://www.mcs.anl.gov/~kazutomo/rdtsc.html
//  Maintainer:       Charles Tsen, 4/2009
// =============================================================================
//  This a measurement header for the Banking benchmark, part of the decimal floating-
//  point benchmark suite. This benchmark was modified from several resources
//  including the rules and condition of the Citibank Dividend Reward Card, and
//  several mortgage calculation. For details, please refer to the following 
//  paper:
//
//      Wang, Tsen, Jhalani, Schulte  "Benchmarks and Performance Analysis
//      of Decimal Floating-Point Applications" from IEEE International
//      Conference on Computer Design, Oct 2007.
//
//  This benchmark emulates a bank-end server in a bank which is capable of
//  doing credit card, normal deposit and CD, and mortgage service. It takes an
//  input file of daily tasks, generated by a test generator located in the
//  testGen directory. sampleTest directory has some sample tests (both big and
//  small, the big test has a "bin_" prefis).  Please see the README for more 
//  info.
// =============================================================================
//  Copyright (C) 2008 MESA LAB - University of Wisconsin
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.
// =============================================================================
// VERSION AND CVS INFO
// Id: $Id: rdtsc.h,v 1.2 2009-05-18 03:09:45 mjanders Exp $
// Date: $Date: 2009-05-18 03:09:45 $
// Author: $Author: mjanders $
// =============================================================================




#if defined(__i386__)

static __inline__ unsigned long long rdtsc(void)
{
  unsigned long long x;
     __asm__ volatile (".byte 0x0f, 0x31" : "=A" (x));
     return x;
}
#elif defined(__x86_64__)

//typedef unsigned long long unsigned long long;

static __inline__ unsigned long long rdtsc(void)
{
  unsigned hi, lo;
  __asm__ __volatile__ ("cpuid\n\t"
  			"rdtsc" : "=a"(lo), "=d"(hi));
  			
  return ( (unsigned long long)lo)|( ((unsigned long long)hi)<<32 );
}

static __inline__ unsigned long long rdtsc_overhead(void)
{
  unsigned hi, lo;
  unsigned long long subtime;

  __asm__ __volatile__ ("cpuid");
  __asm__ __volatile__ ("rdtsc" : "=a"(lo), "=d"(hi));
  subtime = ((unsigned long long)lo)|( ((unsigned long long)hi)<<32);
  __asm__ __volatile__ ("cpuid");
  __asm__ __volatile__ ("rdtsc" : "=a"(lo), "=d"(hi));
  
  __asm__ __volatile__ ("cpuid");
  __asm__ __volatile__ ("rdtsc" : "=a"(lo), "=d"(hi));
  subtime = ((unsigned long long)lo)|( ((unsigned long long)hi)<<32);
  __asm__ __volatile__ ("cpuid");
  __asm__ __volatile__ ("rdtsc" : "=a"(lo), "=d"(hi));
  
  __asm__ __volatile__ ("cpuid");
  __asm__ __volatile__ ("rdtsc" : "=a"(lo), "=d"(hi));
  subtime = ((unsigned long long)lo)|( ((unsigned long long)hi)<<32);
  __asm__ __volatile__ ("cpuid");
  __asm__ __volatile__ ("rdtsc" : "=a"(lo), "=d"(hi));
  subtime = (((unsigned long long)lo)|( ((unsigned long long)hi)<<32)) - subtime;
  
  return subtime;
}

#elif defined(__powerpc__)

typedef unsigned long long unsigned long long;
%
static __inline__ unsigned long long rdtsc(void)
{
  unsigned long long result=0;
  unsigned long int upper, lower,tmp;
  __asm__ volatile(
                "0:                  \n"
                "\tmftbu   %0           \n"
                "\tmftb    %1           \n"
                "\tmftbu   %2           \n"
                "\tcmpw    %2,%0        \n"
                "\tbne     0b         \n"
                : "=r"(upper),"=r"(lower),"=r"(tmp)
                );
  result = upper;
  result = result<<32;
  result = result|lower;

  return(result);
}

#endif
